# Generated by Django 5.0.1 on 2024-01-13 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_orderplaced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='city',
        ),
    ]
